<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.2 (doctrine2-annotation) on 2016-09-07 17:33:32.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * AppBundle\Entity\Agenda
 *
 * @ORM\Entity(repositoryClass="AgendaRepository")
 * @ORM\Table(name="agenda", indexes={@ORM\Index(name="fk_agenda_usuario1_idx", columns={"usuario_id"}), @ORM\Index(name="fk_agenda_disponibilidad1_idx", columns={"disponibilidad_id"})})
 */
class Agenda
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $usuario_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $disponibilidad_id;

    /**
     * @ORM\ManyToOne(targetEntity="Usuario", inversedBy="agendas")
     * @ORM\JoinColumn(name="usuario_id", referencedColumnName="id", nullable=false)
     */
    protected $usuario;

    /**
     * @ORM\ManyToOne(targetEntity="Disponibilidad", inversedBy="agendas")
     * @ORM\JoinColumn(name="disponibilidad_id", referencedColumnName="id", nullable=false)
     */
    protected $disponibilidad;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \AppBundle\Entity\Agenda
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of usuario_id.
     *
     * @param integer $usuario_id
     * @return \AppBundle\Entity\Agenda
     */
    public function setUsuarioId($usuario_id)
    {
        $this->usuario_id = $usuario_id;

        return $this;
    }

    /**
     * Get the value of usuario_id.
     *
     * @return integer
     */
    public function getUsuarioId()
    {
        return $this->usuario_id;
    }

    /**
     * Set the value of disponibilidad_id.
     *
     * @param integer $disponibilidad_id
     * @return \AppBundle\Entity\Agenda
     */
    public function setDisponibilidadId($disponibilidad_id)
    {
        $this->disponibilidad_id = $disponibilidad_id;

        return $this;
    }

    /**
     * Get the value of disponibilidad_id.
     *
     * @return integer
     */
    public function getDisponibilidadId()
    {
        return $this->disponibilidad_id;
    }

    /**
     * Set Usuario entity (many to one).
     *
     * @param \AppBundle\Entity\Usuario $usuario
     * @return \AppBundle\Entity\Agenda
     */
    public function setUsuario(Usuario $usuario = null)
    {
        $this->usuario = $usuario;

        return $this;
    }

    /**
     * Get Usuario entity (many to one).
     *
     * @return \AppBundle\Entity\Usuario
     */
    public function getUsuario()
    {
        return $this->usuario;
    }

    /**
     * Set Disponibilidad entity (many to one).
     *
     * @param \AppBundle\Entity\Disponibilidad $disponibilidad
     * @return \AppBundle\Entity\Agenda
     */
    public function setDisponibilidad(Disponibilidad $disponibilidad = null)
    {
        $this->disponibilidad = $disponibilidad;

        return $this;
    }

    /**
     * Get Disponibilidad entity (many to one).
     *
     * @return \AppBundle\Entity\Disponibilidad
     */
    public function getDisponibilidad()
    {
        return $this->disponibilidad;
    }

    public function __sleep()
    {
        return array('id', 'usuario_id', 'disponibilidad_id');
    }
}